import Header from '@/components/Header'
import './globals.css'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'Layerswap Explorer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex min-h-screen flex-col overflow- items-center max-w-6xl mx-auto'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
